In [32]:
import pandas as pd

In [33]:
df=pd.read_csv('House_price.csv')
df

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4543,84556.63627,5.092459,6.723412,2.42,31797.31744,1.326847e+06,"97160 Tracy Junction\nErinborough, WY 73884"
4544,82732.98111,5.332712,6.198476,3.49,41136.52722,1.252664e+06,"0630 Wilson Shoal\nNorth Philip, AK 91611"
4545,65694.05127,6.436741,6.704929,3.14,43406.71203,1.359763e+06,"PSC 2681, Box 5759\nAPO AA 82431-2879"
4546,76061.35071,7.148713,7.546066,6.30,40876.96459,1.778013e+06,"04117 Bennett Greens\nGonzalezfort, NJ 86640-8362"
4547,66935.47508,6.376390,8.513826,5.47,17573.61710,1.109059e+06,55454 M

In [34]:
df.shape

(4548, 7)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4548 entries, 0 to 4547
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Avg. Area Income    4548 non-null   float64
 1   House Age           4548 non-null   float64
 2   Number of Rooms     4548 non-null   float64
 3   Number of Bedrooms  4548 non-null   float64
 4   Area Population     4548 non-null   float64
 5   Price               4548 non-null   float64
 6   Address             4548 non-null   str
dtypes: float64(6), str(1)
memory usage: 248.8 KB

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.isnull().sum()

Avg. Area Income      0
House Age             0
Number of Rooms       0
Number of Bedrooms    0
Area Population       0
Price                 0
Address               0
dtype: int64

In [38]:
df.describe()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price
count,4548.000000,4548.000000,4548.000000,4548.000000,4548.000000,4.548000e+03
mean,68611.700818,5.978918,6.987646,3.981693,36187.469334,1.233916e+06
std,10686.487761,0.990850,1.006587,1.230939,9910.189915,3.545676e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61485.150192,5.332187,6.299692,3.140000,29423.163510,9.977751e+05
50%,68817.036575,5.960872,7.002245,4.050000,36215.560985,1.234571e+06
75%,75820.741747,6.658368,7.665871,4.490000,42880.554642,1.470616e+06
max,107701.748400,9.519088,10.759588,6.500000,69592.040240,2.469066e+06

In [39]:
# Convert "Number of Rooms" and "Number of Bedrooms" float to int
df[['Number of Rooms', 'Number of Bedrooms']]=df[['Number of Rooms', 'Number of Bedrooms']].astype(int)

In [40]:
# Similarly " House Age" & "Area Population"
df['House Age'] = df['House Age'].round().astype(int)
df['House Age'] = df['House Age'].round(1)

In [42]:
(df['Number of Bedrooms'] > df['Number of Rooms']).sum()

np.int64(2)

In [43]:
df=df[df['Number of Bedrooms'] <= df['Number of Rooms']].reset_index(drop=True)

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4546 entries, 0 to 4545
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Avg. Area Income    4546 non-null   float64
 1   House Age           4546 non-null   int64
 2   Number of Rooms     4546 non-null   int64
 3   Number of Bedrooms  4546 non-null   int64
 4   Area Population     4546 non-null   float64
 5   Price               4546 non-null   float64
 6   Address             4546 non-null   str
dtypes: float64(3), int64(3), str(1)
memory usage: 248.7 KB

In [53]:
df.describe()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price
count,4545.000000,4545.000000,4545.000000,4545.000000,4545.000000,4.545000e+03
mean,68617.391386,5.976018,6.492629,3.732453,36194.582300,1.234330e+06
std,10686.698744,1.038263,1.045825,1.223006,9905.086004,3.541567e+05
min,17796.631190,3.000000,3.000000,2.000000,172.610686,1.593866e+04
25%,61492.921590,5.000000,6.000000,3.000000,29425.406200,9.982409e+05
50%,68827.555030,6.000000,7.000000,4.000000,36215.962550,1.234630e+06
75%,75823.570650,7.000000,7.000000,4.000000,42889.666100,1.471031e+06
max,107701.748400,10.000000,10.000000,6.000000,69592.040240,2.469066e+06

In [45]:
df['Address'].nunique()

4546

In [46]:
df['Address']

0       208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1       188 Johnson Views Suite 079\nLake Kathleen, CA...
2       9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3                               USS Barnett\nFPO AP 44820
4                              USNS Raymond\nFPO AE 09386
                              ...
4541          97160 Tracy Junction\nErinborough, WY 73884
4542            0630 Wilson Shoal\nNorth Philip, AK 91611
4543                PSC 2681, Box 5759\nAPO AA 82431-2879
4544    04117 Bennett Greens\nGonzalezfort, NJ 86640-8362
4545                                              55454 M
Name: Address, Length: 4546, dtype: str

In [47]:
df['Address'].sample(8, random_state=1).to_list()

['65120 Reyes Tunnel Suite 330\nWest Rebeccaport, MS 37254',
 'PSC 5511, Box 3978\nAPO AA 43113',
 '43074 Armstrong Wall\nWest Timothychester, NH 29497-5681',
 '9657 Russell Fords Apt. 246\nKennedymouth, CO 46084-1358',
 '4049 Marshall Court\nNorth Richardchester, CA 72472-7881',
 '90376 Angela Parkway\nWest Daisy, NH 27808-9481',
 'Unit 9831 Box 7128\nDPO AA 54705',
 '8489 Johnson Throughway\nWest Brianna, NV 24375']

In [48]:
df['State'] = df['Address'].str.extract(r'([A-Z]{2})\s\d{5}(?:-\d{4})?$')
df['State']

0        NE
1        CA
2        WI
3        AP
4        AE
       ...
4541     WY
4542     AK
4543     AA
4544     NJ
4545    NaN
Name: State, Length: 4546, dtype: str

In [49]:
df['State'].isnull().sum()

np.int64(1)

In [50]:
# Only One null state so I want to drop it
df = df.dropna(subset=['State']).reset_index(drop=True)

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4545 entries, 0 to 4544
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Avg. Area Income    4545 non-null   float64
 1   House Age           4545 non-null   int64
 2   Number of Rooms     4545 non-null   int64
 3   Number of Bedrooms  4545 non-null   int64
 4   Area Population     4545 non-null   float64
 5   Price               4545 non-null   float64
 6   Address             4545 non-null   str
 7   State               4545 non-null   str
dtypes: float64(3), int64(3), str(2)
memory usage: 284.2 KB

In [52]:
df.shape

(4545, 8)

In [59]:
df['State'].unique()

<StringArray>
['NE', 'CA', 'WI', 'AP', 'AE', 'KS', 'CO', 'TN', 'AA', 'NM', 'PW', 'AR', 'HI',
 'ME', 'IN', 'MI', 'DE', 'AZ', 'MA', 'MN', 'AL', 'NY', 'NV', 'VA', 'ID', 'OK',
 'NH', 'MO', 'WV', 'WY', 'MH', 'UT', 'SD', 'CT', 'AK', 'WA', 'RI', 'NJ', 'KY',
 'NC', 'IA', 'VT', 'FM', 'ND', 'LA', 'MP', 'OR', 'TX', 'DC', 'PR', 'MT', 'AS',
 'OH', 'MS', 'IL', 'VI', 'GA', 'PA', 'MD', 'SC', 'GU', 'FL']
Length: 62, dtype: str

In [61]:
print(df['State'].value_counts())

State
AP    153
AA    152
AE    151
KY     85
GU     84
     ...
AK     62
KS     59
MD     55
IL     53
VI     48
Name: count, Length: 62, dtype: int64